# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 152aabc3b59c5baf370a8fd3d7af250958e25c2262f10ad5d8a81c48014a223e5449b1242b3ff7a95e1d7e7a22a18d6e42c0a312a640bdd3db5beb95b2765537

test:
  secret_key_base: ad156bcffd43ebaebdac1deca2b20077c4e7aeecaddd72948159185212209e5bf166685ccc9d0897341bbe06f090eef0617fb38b1b9c2fcbf49915a382957ca9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
